### ISSUE TITLE
DataExtractor -> couldnt open <filename>

### ISSUE THREAD

**Issue by Feuerdraht** [CypherCore/CypherCore#33]
Hi.
First: Thanks for your work! Really appreciated.

I have tried to use the dataextractor and i get an error.
Maps extractor is running fine. When then the vamps are started, 
it works for a while and the stops with the following msg: 

```
.  .  .
Extracting File003B4B5F.xxx
Extracting File002EB47E.xxx
Extracting File002C6D7C.xxx
Done!
Processing Map 0
Extracting FILE351391:8X.xxx......26%
No such file.
Couldn't open RootWmo!!!
WMOInstance.WMOInstance: couldn't open FILE351391:8X.xxx
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'FILE351391:8X.xxx' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DataExtractor.Vmap.ADTFile.init(UInt32 map_num, UInt32 originalMapId) in D:\cyphercore-tools\Source\DataExtractor\Vmap\Adt.cs:line 139
   at DataExtractor.Vmap.VmapFile.ParsMapFiles() in D:\cyphercore-tools\Source\DataExtractor\Vmap\VmapFile.cs:line 141
   at DataExtractor.Program.ExtractVMaps() in D:\cyphercore-tools\Source\DataExtractor\Program.cs:line 305
   at DataExtractor.Program.Main(String[] args) in D:\cyphercore-tools\Source\DataExtractor\Program.cs:line 105
```

I did a fresh compile (VS2019, Win10 20H2) and still:
mapextractor cant find a file it looks for...
I can run the extractors from Trinity Master against the used client error-free and it generates everything just fine.

Please excuse me, if this is not an issue and i am just too dumb to use the generator ;) 

Thanks in advance for your help.

**Comment by MaxtorCoder** [comment]
Oooff, this is a nice one hahah, if this isn't resolved tonight I'll fix it rq.
