### ISSUE TITLE
Server.cs:line 60 WorldManager.cs:line 401

### ISSUE THREAD

**Issue by Greyisttot** [CypherCore/CypherCore#37]
```
/\  _`\                 /\ \
\ \ \/\_\  __  __  _____\ \ \___      __   _ __
 \ \ \/_/_/\ \/\ \/\ '__`\ \  _ `\  /'__`\/\`'__\
  \ \ \L\ \ \ \_\ \ \ \L\ \ \ \ \ \/\  __/\ \ \/
   \ \____/\/`____ \ \ ,__/\ \_\ \_\ \____\\ \_\
    \/___/  `/___/> \ \ \/  \/_/\/_/\/____/ \/_/
               /\___/\ \_\
               \/__/  \/_/                   Core
https://github.com/CypherCore/CypherCore

Connected to MySQL(ver: 5.5.5-10.4.15-MariaDB-log) Database: 1_auth
Connected to MySQL(ver: 5.5.5-10.4.15-MariaDB-log) Database: 1_characters
Connected to MySQL(ver: 5.5.5-10.4.15-MariaDB-log) Database: 1_world
Connected to MySQL(ver: 5.5.5-10.4.15-MariaDB-log) Database: 1_hotfixes
Updating 1_auth database...
1_auth database is up-to-date! Containing 15 new and 178 archived updates.
Updating 1_characters database...
1_characters database is up-to-date! Containing 7 new and 105 archived updates.
Updating 1_world database...
1_world database is up-to-date! Containing 374 new and 3159 archived updates.
Updating 1_hotfixes database...
1_hotfixes database is up-to-date! Containing 67 new and 301 archived updates.
Realm running as realm ID 1
Using World DB: TDB 837.20101
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
Client cache version set to: 0
Using enUS DBC Locale
Using DataDir ./Data
WORLD: MMap data directory is: ./Data\mmaps
VMap support included. LineOfSight: True, getHeight: True, indoorCheck: True
VMap data directory is: ./Data\vmaps
Loading Cypher Strings...
Loaded 979 CypherStrings in 12 ms
Initialize DataStorage...
CallingMember: UnhandledExceptionHandler ExceptionMessage: Object reference not set to an instance of an object.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Game.WorldManager.SetInitialWorldSettings() in C:\Visual Studio Files\CypherCore\Source\Game\Server\WorldManager.cs:line 401
   at WorldServer.Server.Main() in C:\Visual Studio Files\CypherCore\Source\WorldServer\Server.cs:line 60
```

**Comment by hondacrx** [comment]
you have all the client files in the right folder?

**Comment by Greyisttot** [comment]
@hondacrx 

```
C:\CypherCore>C:\CypherCore\WorldServer.exe
 ____                    __
/\  _`\                 /\ \
\ \ \/\_\  __  __  _____\ \ \___      __   _ __
 \ \ \/_/_/\ \/\ \/\ '__`\ \  _ `\  /'__`\/\`'__\
  \ \ \L\ \ \ \_\ \ \ \L\ \ \ \ \ \/\  __/\ \ \/
   \ \____/\/`____ \ \ ,__/\ \_\ \_\ \____\\ \_\
    \/___/  `/___/> \ \ \/  \/_/\/_/\/____/ \/_/
               /\___/\ \_\
               \/__/  \/_/                   Core
https://github.com/CypherCore/CypherCore

Connected to MySQL(ver: 5.5.5-10.4.15-MariaDB-log) Database: 1_auth
Connected to MySQL(ver: 5.5.5-10.4.15-MariaDB-log) Database: 1_characters
Connected to MySQL(ver: 5.5.5-10.4.15-MariaDB-log) Database: 1_world
Connected to MySQL(ver: 5.5.5-10.4.15-MariaDB-log) Database: 1_hotfixes
Updating 1_auth database...
1_auth database is up-to-date! Containing 15 new and 178 archived updates.
Updating 1_characters database...
1_characters database is up-to-date! Containing 7 new and 105 archived updates.
Updating 1_world database...
1_world database is up-to-date! Containing 374 new and 3159 archived updates.
Updating 1_hotfixes database...
1_hotfixes database is up-to-date! Containing 67 new and 301 archived updates.
Realm running as realm ID 1
Using World DB: TDB 837.20101
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
Client cache version set to: 0
Using enUS DBC Locale
Using DataDir ./Data
WORLD: MMap data directory is: ./Data\mmaps
VMap support included. LineOfSight: True, getHeight: True, indoorCheck: True
VMap data directory is: ./Data\vmaps
Loading Cypher Strings...
Loaded 979 CypherStrings in 11 ms
Initialize DataStorage...
Unable to load db2 files for enUS locale specified in DBC.Locale config!
Loading hotfix blobs...
CallingMember: UnhandledExceptionHandler ExceptionMessage: Object reference not set to an instance of an object.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Game.DataStorage.DB2Manager.LoadHotfixBlob(BitSet availableDb2Locales) in C:\Visual Studio Files\CypherCore\Source\Game\DataStorage\DB2Manager.cs:line 702
   at Game.WorldManager.SetInitialWorldSettings() in C:\Visual Studio Files\CypherCore\Source\Game\Server\WorldManager.cs:line 364
   at WorldServer.Server.Main() in C:\Visual Studio Files\CypherCore\Source\WorldServer\Server.cs:line 60
```
