### ISSUE TITLE
Starting World Server Error.

### ISSUE THREAD

**Issue by Smokey-Dev** [CypherCore/CypherCore#41]
Loaded 0 CypherStrings. DB table `trinity_string` is empty.
Initialize DataStorage...
CallingMember: UnhandledExceptionHandler ExceptionMessage: Object of type 'System.UInt32' cannot be converted to type 'System.Int32[]'.
Unhandled exception. System.ArgumentException: Object of type 'System.UInt32' cannot be converted to type 'System.Int32[]'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at Game.DataStorage.WDC3Row.As[T]() in C:\Users\***\Desktop\***Source\CypherCore\Source\Game\DataStorage\ClientReader\DBReader.cs:line 411
   at Game.DataStorage.DBReader.Read[T](BitSet availableDb2Locales, String db2Path, String fileName, HotfixStatements preparedStatement, HotfixStatements preparedStatementLocale, UInt32& loadedFileCount) in C:\Users\***\Desktop\***Source\CypherCore\Source\Game\DataStorage\ClientReader\DBReader.cs:line 58
   at Game.DataStorage.CliDB.<LoadStores>g__ReadDB2|0_0[T](String fileName, HotfixStatements preparedStatement, HotfixStatements preparedStatementLocale, <>c__DisplayClass0_0& ) in C:\Users\***\Desktop\***Source\CypherCore\Source\Game\DataStorage\CliDB.cs:line 50
   at Game.DataStorage.CliDB.LoadStores(String dataPath, Locale defaultLocale) in C:\Users\***\Desktop\***Source\CypherCore\Source\Game\DataStorage\CliDB.cs:line 47
   at Game.WorldManager.SetInitialWorldSettings() in C:\Users\***\Desktop\***Source\CypherCore\Source\Game\Server\WorldManager.cs:line 403
   at WorldServer.Server.Main() in C:\Users\***\Desktop\*** Source\CypherCore\Source\WorldServer\Server.cs:line 60

**Comment by MaxtorCoder** [comment]
Sounds like outdated db2s
