### ISSUE TITLE
Unhandled exception on command "account create"

### ISSUE THREAD

**Issue by kakukkokkal** [CypherCore/CypherCore#43]
Freshly installed master, commit id: ea4014cf0c6852952bcc7c88df8e55ec2af3cf4f 
It should print error message instead of crashing
See log:
```
Cypher>> account create a
CallingMember: UnhandledExceptionHandler ExceptionMessage: Exception has been thrown by the target of an invocation.
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Game.AccountManager.CreateAccount(String username, String password, String email, UInt32 bnetAccountId, Byte bnetIndex) in /source/Source/Game/Accounts/AccountManager.cs:line 45
   at Game.Chat.AccountCommands.HandleAccountCreateCommand(CommandHandler handler, String accountName, String password, String email) in /source/Source/Game/Chat/Commands/AccountCommands.cs:line 98
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Game.Chat.ChatCommandNode.Invoke(CommandHandler handler, StringArguments args) in /source/Source/Game/Chat/CommandManager.cs:line 406
   at Game.Chat.ChatCommandNode.TryExecuteCommand(CommandHandler handler, String cmdStr) in /source/Source/Game/Chat/CommandManager.cs:line 223
   at Game.Chat.CommandHandler._ParseCommands(String text) in /source/Source/Game/Chat/CommandHandler.cs:line 65
   at Game.Chat.ConsoleHandler.ParseCommands(String str) in /source/Source/Game/Chat/CommandHandler.cs:line 756
   at Game.Chat.CommandManager.InitConsole() in /source/Source/Game/Chat/CommandManager.cs:line 139
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Thread.StartCallback()

```

**Comment by Fabi** [comment]
We might want to deprecate that command @hondacrx since we make full use of bnet accounts?

**Comment by kakukkokkal** [comment]
@Fabi other commands (one bnetaccount subcommand, I don't remember which and I don't have my PC here) also does similar crashes
