### ISSUE TITLE
Exception on logon

### ISSUE THREAD

**Issue by kakukkokkal** [CypherCore/CypherCore#44]
Using the latest commit (56d9dc6190a14f3ffbcbe002d0d14d1be020097e) on authentication the following exception happens (I've removed earlier logs as they can contain sensitive data):
```
cyphercore-authserver-1     | Unhandled exception. Google.Protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
cyphercore-authserver-1     |    at Google.Protobuf.ParsingPrimitives.ParseTag(ReadOnlySpan`1& buffer, ParserInternalState& state)
cyphercore-authserver-1     |    at Google.Protobuf.CodedInputStream.ReadTag()
cyphercore-authserver-1     |    at Bgs.Protocol.Account.V1.GetAccountStateRequest.MergeFrom(CodedInputStream input) in /source/Source/Framework/Proto/AccountService.cs:line 1270
cyphercore-authserver-1     |    at BNetServer.BnetServiceHandler.Invoke(Session session, UInt32 token, CodedInputStream stream) in /source/Source/BNetServer/Managers/LoginServiceManager.cs:line 160
cyphercore-authserver-1     |    at BNetServer.Networking.Session.ReadHandler(Byte[] data, Int32 receivedLength) in /source/Source/BNetServer/Networking/Session.cs:line 105
cyphercore-authserver-1     |    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
cyphercore-authserver-1     |    at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
cyphercore-authserver-1     |    at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
cyphercore-authserver-1     |    at System.Threading.QueueUserWorkItemCallback.Execute()
cyphercore-authserver-1     |    at System.Threading.ThreadPoolWorkQueue.Dispatch()
cyphercore-authserver-1     |    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
cyphercore-authserver-1     |    at System.Threading.Thread.StartCallback()
```

**Comment by kakukkokkal** [comment]
Note: I couldn't reproduce it after core restart
